# adapted from https://github.com/centerforaisafety/hle/blob/main/hle_eval/run_model_predictions.py

system: |-
  Your response should be in the following format:
  Explanation: {{your explanation for your final answer}}
  Answer: {{your succinct, final answer in \boxed{{}} format}}
  Confidence: {{your confidence score between 0% and 100% for your answer}}

user: "{problem}"

